using System;using System.Data;using System.Drawing;using System.IO;using System.Linq;using System.Text;using System.Windows.Forms;using WindowsFormsApp1.Data;
namespace WindowsFormsApp1
{
    public class FinanceiroForm:Form
    {
        private readonly OperacoesRepository repositorio=new OperacoesRepository();private readonly DataGridView tabela=new DataGridView();private readonly Label total=new Label();
        public FinanceiroForm(){Text="Financeiro - Hotel Bennett's";MinimumSize=new Size(760,520);TableLayoutPanel raiz=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),ColumnCount=1,RowCount=3};raiz.RowStyles.Add(new RowStyle(SizeType.Absolute,70));raiz.RowStyles.Add(new RowStyle(SizeType.Percent,100));raiz.RowStyles.Add(new RowStyle(SizeType.Absolute,58));total.Dock=DockStyle.Fill;total.Font=new Font("Segoe UI",18,FontStyle.Bold);total.TextAlign=ContentAlignment.MiddleLeft;tabela.Dock=DockStyle.Fill;tabela.ReadOnly=true;tabela.AllowUserToAddRows=false;tabela.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;FlowLayoutPanel acoes=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(0,10,0,0)};Button fechar=new Button{Text="Fechar",Size=new Size(100,34)};fechar.Click+=(s,e)=>Close();Button exportar=new Button{Text="Exportar CSV",Size=new Size(125,34)};exportar.Click+=(s,e)=>Exportar();Button atualizar=new Button{Text="Atualizar",Size=new Size(105,34)};atualizar.Click+=(s,e)=>Carregar();acoes.Controls.Add(fechar);acoes.Controls.Add(exportar);acoes.Controls.Add(atualizar);raiz.Controls.Add(total,0,0);raiz.Controls.Add(tabela,0,1);raiz.Controls.Add(acoes,0,2);Controls.Add(raiz);Carregar();}
        private void Carregar(){tabela.DataSource=repositorio.Financeiro();total.Text="Receita registrada: R$ "+repositorio.Receita().ToString("N2");}
        private void Exportar(){using(SaveFileDialog s=new SaveFileDialog{Filter="Arquivo CSV|*.csv",FileName="financeiro.csv"})if(s.ShowDialog()==DialogResult.OK){StringBuilder b=new StringBuilder();b.AppendLine(string.Join(";",tabela.Columns.Cast<DataGridViewColumn>().Select(c=>c.HeaderText)));foreach(DataGridViewRow r in tabela.Rows)b.AppendLine(string.Join(";",r.Cells.Cast<DataGridViewCell>().Select(c=>(c.Value??"").ToString().Replace(";",","))));File.WriteAllText(s.FileName,b.ToString(),Encoding.UTF8);MessageBox.Show("Financeiro exportado.");}}
    }
}
