using System;using System.Drawing;using System.Windows.Forms;using WindowsFormsApp1.Data;
namespace WindowsFormsApp1
{
    public class SacForm:Form
    {
        private readonly OperacoesRepository repositorio=new OperacoesRepository();private readonly TextBox cliente=new TextBox(),assunto=new TextBox(),descricao=new TextBox();private readonly DataGridView tabela=new DataGridView();
        public SacForm(){Text="SAC - Hotel Bennett's";MinimumSize=new Size(760,540);TableLayoutPanel raiz=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),ColumnCount=1,RowCount=3};raiz.RowStyles.Add(new RowStyle(SizeType.Absolute,180));raiz.RowStyles.Add(new RowStyle(SizeType.Percent,100));raiz.RowStyles.Add(new RowStyle(SizeType.Absolute,58));GroupBox dados=new GroupBox{Text="Novo atendimento",Dock=DockStyle.Fill,Padding=new Padding(16)};TableLayoutPanel f=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=3};f.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,110));f.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Adicionar(f,"Cliente:",cliente,0);Adicionar(f,"Assunto:",assunto,1);descricao.Multiline=true;Adicionar(f,"Descrição:",descricao,2);dados.Controls.Add(f);tabela.Dock=DockStyle.Fill;tabela.ReadOnly=true;tabela.AllowUserToAddRows=false;tabela.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;tabela.SelectionMode=DataGridViewSelectionMode.FullRowSelect;FlowLayoutPanel acoes=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(0,10,0,0)};Button fechar=new Button{Text="Fechar",Size=new Size(100,34)};fechar.Click+=(s,e)=>Close();Button resolver=new Button{Text="Marcar resolvido",Size=new Size(140,34)};resolver.Click+=(s,e)=>Resolver();Button abrir=new Button{Text="Abrir chamado",Size=new Size(125,34)};abrir.Click+=(s,e)=>Abrir();acoes.Controls.Add(fechar);acoes.Controls.Add(resolver);acoes.Controls.Add(abrir);raiz.Controls.Add(dados,0,0);raiz.Controls.Add(tabela,0,1);raiz.Controls.Add(acoes,0,2);Controls.Add(raiz);Carregar();}
        private static void Adicionar(TableLayoutPanel p,string texto,Control c,int linha){p.Controls.Add(new Label{Text=texto,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft},0,linha);c.Dock=DockStyle.Fill;p.Controls.Add(c,1,linha);}
        private void Carregar(){tabela.DataSource=repositorio.ListarSac();}
        private void Abrir(){if(cliente.Text.Trim().Length<2||assunto.Text.Trim().Length<2){MessageBox.Show("Informe o cliente e o assunto.");return;}repositorio.AbrirChamado(cliente.Text.Trim(),assunto.Text.Trim(),descricao.Text.Trim());cliente.Clear();assunto.Clear();descricao.Clear();Carregar();}
        private void Resolver(){if(tabela.CurrentRow==null)return;repositorio.FecharChamado(Convert.ToInt64(tabela.CurrentRow.Cells["Id"].Value));Carregar();}
    }
}
